# generated by mutilz cli at 2025-06-02 20:28:51
import dataclasses
import functools
import logging
import time
import typing

import ida_bytes
import ida_funcs
import ida_kernwin
import ida_segment
import ida_ua
import idaapi
import idautils
import idc
import mutilz.settings
import mutilz.actions as actions
import mutilz.helpers.ida as ida_helpers


logger = logging.getLogger("mutilz.actions.create_dir_paths_from_strings")


def execute_action(start_ea: int, end_ea: int, settings: mutilz.settings.ActionSettings):
    print(f"Hello! Called execute_action with range 0x{start_ea:X} - 0x{end_ea:X}")
    

@dataclasses.dataclass
class CreateDirPathsFromStringsActionHandler(ida_helpers.BaseActionHandler):
    """Create Dir Paths From Strings"""
    action_name: str = "mutilz:create_dir_paths_from_strings"
    action_label: str = "Create Dir Paths From Strings"
    icon: int = 171

    @classmethod
    def settings(cls) -> mutilz.settings.ActionSettings:
        mutilz.settings.reload()
        return mutilz.settings.get_action_config(cls.action_name)

    def get_selected_addresses(self, ctx):
        is_selected, start_ea, end_ea = idaapi.read_range_selection(
            idaapi.get_current_viewer()
        )
        if is_selected:
            return start_ea, end_ea

        # maybe it's the same line?
        p0, p1 = ida_kernwin.twinpos_t(), ida_kernwin.twinpos_t()
        ida_kernwin.read_selection(ctx.widget, p0, p1)
        p0.place(ctx.widget)
        p1.place(ctx.widget)
        if p0.at and p1.at:
            start_ea = p0.at.toea()
            end_ea = p1.at.toea()
            if start_ea == end_ea:
                start_ea = idc.get_item_head(start_ea)
                end_ea = idc.get_item_end(start_ea)
                return start_ea, end_ea

        # if we are here, we haven't selected anything, so we use the current address
        start_ea = idaapi.get_screen_ea()
        try:
            end_ea = ida_kernwin.ask_addr(start_ea, "Enter end address for selection:")
        finally:
            # restore the cursor to the original address
            idc.jumpto(start_ea)

        if end_ea and end_ea <= start_ea:
            print(
                f"Error: End address 0x{end_ea:X} must be greater than start address 0x{start_ea:X}."
            )
            end_ea = None

        if end_ea is None:
            # if we canceled the dialog, let's assume the user wants
            # to select just the line they're on
            end_ea = idc.get_item_end(start_ea)
            print(f"No end address selected, using line end: 0x{end_ea:X}")

        return start_ea, end_ea

    def func_at(self, curr_ea: int) -> ida_funcs.func_t:
        func = ida_funcs.get_func(curr_ea)
        if not func:
            logger.error("No function at current position!")
            return
        return func
                    
    def activate(self, ctx):
        curr_ea = idaapi.get_screen_ea()
        try:
            # start_ea, end_ea = self.get_selected_addresses(ctx) 
            # or 
            # func = self.func_at(curr_ea)
            execute_action(start_ea, end_ea, self.settings())
        finally:
            idc.jumpto(curr_ea)

    def update(self, ctx):
        match ctx.widget_type:
            case idaapi.BWN_DISASM:
                return idaapi.AST_ENABLE_FOR_WIDGET
            case _:
                return idaapi.AST_DISABLE_FOR_WIDGET


class CreateDirPathsFromStringsAction(actions.action_t, metaclass=ida_helpers.HookedActionMeta):
    uihook_class = functools.partial(
        ida_helpers.PopUpHook,
        CreateDirPathsFromStringsActionHandler,
        ida_helpers.is_disassembly_widget,
    )


# retrieve the action
def get_action() -> actions.action_t:
    return CreateDirPathsFromStringsAction()

