# generated by mutilz cli at 2025-06-02 21:01:41
import contextlib
import dataclasses
import functools
import logging
import pathlib
import time
import typing

import ida_bytes
import ida_fpro
import ida_funcs
import ida_kernwin
import ida_loader
import ida_segment
import ida_ua
import idaapi
import idautils
import idc

import mutilz.actions as actions
import mutilz.helpers.ida as ida_helpers
import mutilz.settings

logger = logging.getLogger("mutilz.actions.export_functions")


if idaapi.is_idaq():
    from PyQt5 import QtCore, QtGui, QtWidgets  # type: ignore


@contextlib.contextmanager
def qfile_context(filename: pathlib.Path, mode: str = "wt"):
    """Context manager for qfile_t operations.

    Args:
        filename: Path to the file to open
        mode: File open mode (default: "wt" for write text)

    Yields:
        qfile_t instance

    Raises:
        IOError: If file cannot be opened
    """
    file = ida_fpro.qfile_t()
    if not file.open(str(filename), mode):
        raise IOError(f"Failed to open file: {filename}")
    try:
        yield file
    finally:
        file.close()


@dataclasses.dataclass
class ExportDialogSettings:
    """Settings for the export dialog."""

    filename: pathlib.Path
    copy_to_clipboard: bool = False
    recursive: bool = False
    output_format: str = "lst"
    include_types: bool = True
    generate_html: bool = False
    demangle_names: bool = True
    include_local_names: bool = True
    include_dummy_names: bool = True

    def to_ida_loader_format(self) -> int:
        match self.output_format:
            case "asm":
                return ida_loader.OFILE_ASM
            case "lst":
                return ida_loader.OFILE_LST
            case "map":
                return ida_loader.OFILE_MAP
            case "idc":
                return ida_loader.OFILE_IDC
            case _:
                raise ValueError(f"Invalid output format: {self.output_format}")

    def to_ida_loader_flags(self) -> int:
        flags = 0
        if self.generate_html:
            flags |= ida_loader.GENFLG_GENHTML  # OFILE_ASM,OFILE_LST: generate html
        if self.include_types:
            if self.output_format in ["asm", "lst"]:
                flags |= (
                    ida_loader.GENFLG_ASMTYPE
                )  # OFILE_ASM,OFILE_LST: gen information about types too
                flags |= (
                    ida_loader.GENFLG_ASMINC
                )  # OFILE_ASM,OFILE_LST: gen information only about types
            else:
                flags |= (
                    ida_loader.GENFLG_IDCTYPE
                )  # OFILE_IDC: gen only information about types
        if self.output_format == "map":
            flags |= ida_loader.GENFLG_MAPSEG  # OFILE_MAP: generate map of segments
            if self.demangle_names:
                flags |= ida_loader.GENFLG_MAPDMNG  # OFILE_MAP: demangle names
            if self.include_dummy_names:
                flags |= ida_loader.GENFLG_MAPNAME  # OFILE_MAP: include dummy names
            if self.include_local_names:
                flags |= ida_loader.GENFLG_MAPLOC  # OFILE_MAP: include local names

        return 0


def show_file_save_dialog(func_name: str) -> ExportDialogSettings:
    dialog = QtWidgets.QDialog()
    dialog.setWindowTitle("Export function...")
    layout = QtWidgets.QVBoxLayout()

    # File selection
    file_layout = QtWidgets.QHBoxLayout()
    file_edit = QtWidgets.QLineEdit(func_name)
    browse_btn = QtWidgets.QPushButton("Browse...")
    file_layout.addWidget(file_edit)
    file_layout.addWidget(browse_btn)
    layout.addLayout(file_layout)

    # Checkboxes
    copy_cb = QtWidgets.QCheckBox("Also copy function to clipboard")
    copy_cb.setChecked(ExportDialogSettings.copy_to_clipboard)

    recursive_cb = QtWidgets.QCheckBox("Recursively copy")
    recursive_cb.setChecked(ExportDialogSettings.recursive)

    include_types_cb = QtWidgets.QCheckBox("Include type information")
    include_types_cb.setChecked(ExportDialogSettings.include_types)

    generate_html_cb = QtWidgets.QCheckBox("Generate HTML output")
    generate_html_cb.setChecked(ExportDialogSettings.generate_html)

    demangle_names_cb = QtWidgets.QCheckBox("Demangle names")
    demangle_names_cb.setChecked(ExportDialogSettings.demangle_names)

    include_local_names_cb = QtWidgets.QCheckBox("Include local names")
    include_local_names_cb.setChecked(ExportDialogSettings.include_local_names)

    include_dummy_names_cb = QtWidgets.QCheckBox("Include dummy names")
    include_dummy_names_cb.setChecked(ExportDialogSettings.include_dummy_names)
    layout.addWidget(copy_cb)
    layout.addWidget(recursive_cb)
    layout.addWidget(include_types_cb)
    layout.addWidget(generate_html_cb)
    layout.addWidget(demangle_names_cb)
    layout.addWidget(include_local_names_cb)
    layout.addWidget(include_dummy_names_cb)

    # Output format selection
    format_layout = QtWidgets.QHBoxLayout()
    format_label = QtWidgets.QLabel("Output Format:")
    format_combo = QtWidgets.QComboBox()
    format_combo.addItems(["asm", "lst", "map", "idc"])
    format_layout.addWidget(format_label)
    format_layout.addWidget(format_combo)
    layout.addLayout(format_layout)

    # Buttons
    button_box = QtWidgets.QDialogButtonBox(
        QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel
    )
    layout.addWidget(button_box)

    dialog.setLayout(layout)

    # Connect signals
    def browse_clicked():
        fname, _ = QtWidgets.QFileDialog.getSaveFileName(
            dialog,
            "Export function...",
            file_edit.text(),
            "All Files (*)",
        )
        if fname:
            file_edit.setText(fname)

    browse_btn.clicked.connect(browse_clicked)
    button_box.accepted.connect(dialog.accept)
    button_box.rejected.connect(dialog.reject)

    if dialog.exec_() == QtWidgets.QDialog.Accepted:
        return ExportDialogSettings(
            filename=pathlib.Path(file_edit.text()),
            copy_to_clipboard=copy_cb.isChecked(),
            recursive=recursive_cb.isChecked(),
            output_format=format_combo.currentText(),
            include_types=include_types_cb.isChecked(),
            generate_html=generate_html_cb.isChecked(),
            demangle_names=demangle_names_cb.isChecked(),
            include_local_names=include_local_names_cb.isChecked(),
            include_dummy_names=include_dummy_names_cb.isChecked(),
        )
    return ExportDialogSettings(filename=pathlib.Path())


def default_filename(func_name: str, output_format: str) -> pathlib.Path:
    return (
        pathlib.Path(ida_loader.get_path(ida_loader.PATH_TYPE_CMD))
        / f"{func_name}.{output_format}"
    )


def execute_action(
    start_ea: int, end_ea: int, settings: mutilz.settings.ActionSettings
):
    # Get Name
    func_name = ida_funcs.get_func_name(start_ea)
    if not func_name:
        func_name = f"func_{start_ea:X}"

    if idaapi.is_idaq():
        export_settings = show_file_save_dialog(func_name)
    else:
        export_settings = ExportDialogSettings(
            filename=default_filename(func_name, "lst"), output_format="lst"
        )

    if not export_settings.filename:
        return False

    if export_settings.recursive:
        pass

    with qfile_context(export_settings.filename, "wt") as file:
        ida_loader.gen_file(
            export_settings.to_ida_loader_format(),
            file.get_fp(),
            start_ea,
            end_ea,
            export_settings.to_ida_loader_flags(),
        )
        logger.info(f"Exported function {func_name} to {export_settings.filename}")

    if export_settings.copy_to_clipboard:
        QtWidgets.QApplication.clipboard().setText(export_settings.filename.read_text())
        logger.info(f"Copied function {func_name} to clipboard")

    return True


@dataclasses.dataclass
class ExportFunctionsActionHandler(ida_helpers.BaseActionHandler):
    """Export Functions"""

    action_name: str = "mutilz:export_functions"
    action_label: str = "Export Functions"
    icon: int = 171

    @classmethod
    def settings(cls) -> mutilz.settings.ActionSettings:
        mutilz.settings.reload()
        return mutilz.settings.get_action_config(cls.action_name)

    def get_selected_addresses(self, ctx):
        is_selected, start_ea, end_ea = idaapi.read_range_selection(
            idaapi.get_current_viewer()
        )
        if is_selected:
            return start_ea, end_ea

        # maybe it's the same line?
        p0, p1 = ida_kernwin.twinpos_t(), ida_kernwin.twinpos_t()
        ida_kernwin.read_selection(ctx.widget, p0, p1)
        p0.place(ctx.widget)
        p1.place(ctx.widget)
        if p0.at and p1.at:
            start_ea = p0.at.toea()
            end_ea = p1.at.toea()
            if start_ea == end_ea:
                start_ea = idc.get_item_head(start_ea)
                end_ea = idc.get_item_end(start_ea)
                return start_ea, end_ea

        # if we are here, we haven't selected anything, so we use the current address
        start_ea = idaapi.get_screen_ea()
        try:
            end_ea = ida_kernwin.ask_addr(start_ea, "Enter end address for selection:")
        finally:
            # restore the cursor to the original address
            idc.jumpto(start_ea)

        if end_ea and end_ea <= start_ea:
            print(
                f"Error: End address 0x{end_ea:X} must be greater than start address 0x{start_ea:X}."
            )
            end_ea = None

        if end_ea is None:
            # if we canceled the dialog, let's assume the user wants
            # to select just the line they're on
            end_ea = idc.get_item_end(start_ea)
            print(f"No end address selected, using line end: 0x{end_ea:X}")

        return start_ea, end_ea

    def func_at(self, curr_ea: int) -> ida_funcs.func_t | None:
        func = ida_funcs.get_func(curr_ea)
        if not func:
            logger.error("No function at current position!")
            return None
        return func

    def activate(self, ctx):
        curr_ea = idaapi.get_screen_ea()
        try:
            func = self.func_at(curr_ea)
            if func:
                execute_action(func.start_ea, func.end_ea, self.settings())
        finally:
            idc.jumpto(curr_ea)

    def update(self, ctx):
        match ctx.widget_type:
            case idaapi.BWN_DISASM:
                return idaapi.AST_ENABLE_FOR_WIDGET
            case _:
                return idaapi.AST_DISABLE_FOR_WIDGET


class ExportFunctionsAction(actions.action_t, metaclass=ida_helpers.HookedActionMeta):
    uihook_class = functools.partial(
        ida_helpers.PopUpHook,
        ExportFunctionsActionHandler,
        ida_helpers.is_disassembly_widget,
    )


# retrieve the action
def get_action() -> actions.action_t:
    return ExportFunctionsAction()
