# generated by mutilz cli at 2025-07-15 09:56:21
import dataclasses
import functools
import logging

import ida_funcs
import idaapi

import mutilz.actions as actions
import mutilz.helpers.ida as ida_helpers
import mutilz.settings

logger = logging.getLogger("mutilz.actions.mark_function_outlined")


@dataclasses.dataclass
class MarkFunctionOutlinedActionHandler(ida_helpers.BaseActionHandler):
    """Mark Function Outlined"""

    action_name: str = "mutilz:mark_function_outlined"
    action_label: str = "Mark Function Outlined"
    icon: int = 171

    @classmethod
    def settings(cls) -> mutilz.settings.ActionSettings:
        mutilz.settings.reload()
        return mutilz.settings.get_action_config(cls.action_name)

    def activate(self, ctx):
        # if ctx.widget_type != idaapi.BWN_FUNCS:
        #     ida_kernwin.warning("This action is only available in the Functions window.")
        #     return 0
        for idx in ctx.chooser_selection:
            func = idaapi.getn_func(idx)
            if func:
                func.flags |= idaapi.FUNC_OUTLINE
                ida_funcs.update_func(func)
            else:
                logger.warning("No function at index %d", idx)
        return 1

    def update(self, ctx):
        match ctx.widget_type:
            case idaapi.BWN_FUNCS:
                return idaapi.AST_ENABLE_FOR_WIDGET
            case _:
                return idaapi.AST_DISABLE_FOR_WIDGET


def is_functions_widget(widget, popup, ctx):
    return idaapi.get_widget_type(widget) == idaapi.BWN_FUNCS


class MarkFunctionOutlinedAction(
    actions.action_t, metaclass=ida_helpers.HookedActionMeta
):
    uihook_class = functools.partial(
        ida_helpers.PopUpHook,
        MarkFunctionOutlinedActionHandler,
        is_functions_widget,
    )


# retrieve the action
def get_action() -> actions.action_t:
    return MarkFunctionOutlinedAction()
