# generated by mutilz cli at 2025-03-18 14:20:21
import array
import collections
import dataclasses
import functools
import io
import itertools
import logging
import re
import struct
import typing
from dataclasses import dataclass, field
from enum import Enum, auto

import ida_allins
import ida_auto
import ida_bytes
import ida_funcs
import ida_hexrays
import ida_ida
import ida_kernwin
import ida_segment
import ida_ua
import idaapi
import idautils
import idc

import capstone
import mutilz.actions as actions
import mutilz.helpers.ida as ida_helpers
import mutilz.settings
from mutilz.actions.force_analyze import ForceAnalyzeActionHandler
from mutilz.helpers.ida import format_addr
from mutilz.logconf import configure_logging

logger = logging.getLogger("mutilz.actions.remove_anti_disassembly")
md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
md.detail = True


class ThreadUtils:
    @staticmethod
    def is_mainthread():
        """
        Return a bool that indicates if this is the main application thread.
        """
        # isinstance(threading.current_thread(), threading._MainThread)
        return idaapi.is_main_thread()

    @staticmethod
    def mainthread(f):
        """
        A debug decorator to ensure that a function is always called from the main thread.
        """

        def wrapper(*args, **kwargs):
            assert ThreadUtils.is_mainthread()
            return f(*args, **kwargs)

        return wrapper

    @staticmethod
    def not_mainthread(f):
        """
        A debug decorator to ensure that a function is never called from the main thread.
        """

        def wrapper(*args, **kwargs):
            assert not ThreadUtils.is_mainthread()
            return f(*args, **kwargs)

        return wrapper


def execute_sync(function, sync_type):
    """
    Synchronize with the disassembler for safe database access.

    Modified from https://github.com/vrtadmin/FIRST-plugin-ida
    """

    @functools.wraps(function)
    def wrapper(*args, **kwargs):
        output = [None]

        #
        # this inline function definition is technically what will execute
        # in the context of the main thread. we use this thunk to capture
        # any output the function may want to return to the user.
        #

        def thunk():
            output[0] = function(*args, **kwargs)
            return 1

        if ThreadUtils.is_mainthread():
            thunk()
        else:
            idaapi.execute_sync(thunk, sync_type)

        # return the output of the synchronized execution
        return output[0]

    return wrapper


execute_read = functools.partial(execute_sync, sync_type=idaapi.MFF_READ)
execute_write = functools.partial(execute_sync, sync_type=idaapi.MFF_WRITE)
execute_ui = functools.partial(execute_sync, sync_type=idaapi.MFF_FAST)
IS_X64 = execute_read(ida_ida.inf_is_64bit)()


# fmt: off
# NOP patterns from the source code
NOP_PATTERNS = [
    # 1-byte NOP
    [0x90],
    # 2-byte XCHG AX,AX
    [0x66, 0x90],
    # 3-byte NOP DWORD ptr [RAX]
    [0x0F, 0x1F, 0x00],
    # 4-byte NOP DWORD ptr [RAX + 0]
    [0x0F, 0x1F, 0x40, 0x00],
    # 5-byte NOP DWORD ptr [RAX + RAX + 0]
    [0x0F, 0x1F, 0x44, 0x00, 0x00],
    # 6-byte NOP WORD ptr [RAX + RAX + 0]
    [0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00],
    # 7-byte NOP DWORD ptr [RAX + 0] (variant)
    [0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00],
    # 8-byte NOP DWORD ptr [RAX + RAX + 0] (variant)
    [0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00],
    # 9-byte NOP WORD ptr [RAX + RAX + 0] (variant)
    [0x66, 0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00],
    # 10-byte NOP with extra prefix
    [0x66, 0x66, 0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00],
    # 11-byte NOP with three 0x66 prefixes
    [0x66, 0x66, 0x66, 0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00],
]

CONDITIONAL_JUMPS = list(range(ida_allins.NN_ja, ida_allins.NN_jz + 1))
ALL_JUMPS = CONDITIONAL_JUMPS + [ida_allins.NN_jmp]
CALL_INSTRUCTIONS = {ida_allins.NN_call, ida_allins.NN_callfi, ida_allins.NN_callni}
CONDITIONAL_JUMPS_MNEMONICS = [
    "ja",
    "jae",
    "jb",
    "jbe",
    "jc",
    "jcxz",
    "jecxz",
    "jrcxz",
    "je",
    "jg",
    "jge",
    "jl",
    "jle",
    "jna",
    "jnae",
    "jnb",
    "jnbe",
    "jnc",
    "jne",
    "jng",
    "jnge",
    "jnl",
    "jnle",
    "jno",
    "jnp",
    "jns",
    "jnz",
    "jo",
    "jp",
    "jpe",
    "jpo",
    "js",
    "jz",
]
ALL_JUMPS_MNEMONICS = CONDITIONAL_JUMPS_MNEMONICS + ["jmp"]

# Define padding pattern (common in anti-disassembly sequences)
PADDING = rb"((\xC0[\xE0-\xFF]\x00)|(\x86|\x8A)[\xC0\xC9\xD2\xDB\xE4\xED\xF6\xFF])"
# --- Reusable Padding Pattern ---
# First, define the raw padding pattern without capturing groups.
PADDING_PATTERN = rb"(?:\xC0[\xE0-\xFF]\x00|(?:\x86|\x8A)[\xC0\xC9\xD2\xDB\xE4\xED\xF6\xFF])"
# (We do not wrap this in a named group here so that we can reuse it inside other groups.)

# --- Enum for Pattern Categories ---
class PatternCategory(Enum):
    MULTI_PART = auto()
    SINGLE_PART = auto()
    JUNK = auto()

# --- Dataclass for Regex Pattern Metadata ---
@dataclass
class RegexPatternMetadata:
    category: PatternCategory
    pattern: bytes  # The regex pattern as a bytes literal
    description: typing.Optional[str] = None
    compiled: typing.Optional[typing.Pattern] = None

    def compile(self, flags=0):
        """Compile the regex if not already done, and return the compiled object."""
        if self.compiled is None:
            self.compiled = re.compile(self.pattern, flags)
        return self.compiled

    @property
    def group_names(self):
        """Return the dictionary mapping group names to their indices."""
        return self.compile().groupindex

@dataclass
class MultiPartPatternMetadata(RegexPatternMetadata):
    category: PatternCategory = field(default=PatternCategory.MULTI_PART, init=False)

    def __post_init__(self):
        # Compile to ensure group names are available.
        _ = self.compile(re.DOTALL)
        required_groups = {"first_jump", "padding", "second_jump"}
        missing = required_groups - set(self.group_names)
        if missing:
            raise ValueError(
                f"MultiPart pattern is missing required groups: {missing}"
            )

@dataclass
class SinglePartPatternMetadata(RegexPatternMetadata):
    category: PatternCategory = field(default=PatternCategory.SINGLE_PART, init=False)

    def __post_init__(self):
        _ = self.compile(re.DOTALL)
        required_groups = {"prefix", "padding", "jump"}
        missing = required_groups - set(self.group_names)
        if missing:
            raise ValueError(
                f"SinglePart pattern is missing required groups: {missing}"
            )

@dataclass
class JunkPatternMetadata(RegexPatternMetadata):
    category: PatternCategory = field(default=PatternCategory.JUNK, init=False)

    def __post_init__(self):
        _ = self.compile(re.DOTALL)
        required_groups = {"junk"}
        missing = required_groups - set(self.group_names)
        if missing:
            raise ValueError("Junk pattern must have a 'junk' group.")
    
# Multi-part jump patterns: pairs of conditional jumps with optional padding
MULTI_PART_PATTERNS = [
    MultiPartPatternMetadata(rb"(?P<first_jump>\x70.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x71.)", "JO ... JNO"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x71.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x70.)", "JNO ... JO"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x72.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x73.)", "JB ... JAE"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x73.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x72.)", "JAE ... JB"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x74.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x75.)", "JE ... JNE"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x75.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x74.)", "JNE ... JE"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x76.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x77.)", "JBE ... JA"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x77.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x76.)", "JA ... JBE"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x78.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x79.)", "JS ... JNS"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x79.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x78.)", "JNS ... JS"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x7A.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x7B.)", "JP ... JNP"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x7B.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x7A.)", "JNP ... JP"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x7C.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x7D.)", "JL ... JGE"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x7D.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x7C.)", "JGE ... JL"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x7E.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x7F.)", "JLE ... JG"),
    MultiPartPatternMetadata(rb"(?P<first_jump>\x7F.)(?P<padding>" + PADDING_PATTERN + rb")*(?P<second_jump>\x7E.)", "JG ... JLE"),
]

# Single-part jump patterns: prefix instruction + optional padding + conditional jump
SINGLE_PART_PATTERNS = [
    SinglePartPatternMetadata(rb"(?P<prefix>\xF8)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "CLC ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xF9)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x76.)", "STC ... JBE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xF9)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x72.)", "STC ... JB"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xA8.)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "TEST AL, imm8 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xA9....)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "TEST EAX, imm32 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xF6..)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "TEST r/m8, imm8 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xF7.....)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "TEST r/m32, imm32 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x84.)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "TEST r/m8, r8 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x85.)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "TEST r/m32, r32 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xA8.)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "TEST AL, imm8 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xA9....)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "TEST EAX, imm32 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xF6..)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "TEST r/m8, imm8 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\xF7.....)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "TEST r/m32, imm32 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x84.)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "TEST r/m8, r8 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x85.)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "TEST r/m32, r32 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x80[\xE0-\xE7]\xFF)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "AND r/m8, 0xFF ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x24\xFF)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "AND AL, 0xFF ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x80[\xC8-\xCF]\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "OR r/m8, 0x00 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x0C\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "OR AL, 0x00 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x80[\xF0-\xF7]\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "XOR r/m8, 0x00 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x34\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x71.)", "XOR AL, 0x00 ... JNO"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x80[\xE0-\xE7]\xFF)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "AND r/m8, 0xFF ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x24\xFF)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "AND AL, 0xFF ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x80[\xC8-\xCF]\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "OR r/m8, 0x00 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x0C\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "OR AL, 0x00 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x80[\xF0-\xF7]\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "XOR r/m8, 0x00 ... JAE"),
    SinglePartPatternMetadata(rb"(?P<prefix>\x34\x00)(?P<padding>" + PADDING_PATTERN + rb")?(?P<jump>\x73.)", "XOR AL, 0x00 ... JAE"),
]


JUNK_PATTERNS = [
    JunkPatternMetadata(rb"(?P<junk>\x0F\x31)", "RDTSC"),
    JunkPatternMetadata(rb"(?P<junk>\x0F[\x80-\x8F]..[\x00\x01]\x00)", "TwoByte Conditional Jump"),
    JunkPatternMetadata(rb"(?P<junk>\xE8..[\x00\x01]\x00)", "Invalid CALL"),
    JunkPatternMetadata(rb"(?P<junk>\x81[\xC0-\xC3\xC5-\xC7]....)", "ADD reg32, imm32"),
    JunkPatternMetadata(rb"(?P<junk>\x80[\xC0-\xC3\xC5-\xC7].)", "ADD reg8, imm8"),
    JunkPatternMetadata(rb"(?P<junk>\x83[\xC0-\xC3\xC5-\xC7].)", "ADD reg32, imm8"),
    JunkPatternMetadata(rb"(?P<junk>\xC6[\xC0-\xC3\xC5-\xC7].)", "MOV reg8, imm8"),
    JunkPatternMetadata(rb"(?P<junk>\xC7[\xC0-\xC3\xC5-\xC7]....)", "MOV reg32, imm32"),
    JunkPatternMetadata(rb"(?P<junk>\xF6[\xD8-\xDB\xDD-\xDF])", "NEG reg8"),
    JunkPatternMetadata(rb"(?P<junk>\x80[\xE8-\xEB\xED-\xEF].)", "AND reg8, imm8"),
    JunkPatternMetadata(rb"(?P<junk>\x81[\xE8-\xEB\xED-\xEF]....)", "AND reg32, imm32"),
    JunkPatternMetadata(rb"(?P<junk>\x68....)", "PUSH imm32"),
    JunkPatternMetadata(rb"(?P<junk>\x6A.)", "PUSH imm8"),
    JunkPatternMetadata(rb"(?P<junk>[\x70-\x7F].)", "Random 112-127"),
    JunkPatternMetadata(rb"(?P<junk>[\x50-\x5F])", "Single-byte PUSH/POP"),
]   


# Define "big instruction" opcode arrays
SINGLE_BYTE_OPCODES = b"\xc8\x05\x0d\x15\x1d\x25\x2d\x35\x3d\x68\xa0\xa1\xa2\xa3\xa9\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xe8\xe9\x69\x81\xc7\xf7"
MED_OPCODES = b"\xa0\xa1\xa2\xa3\x00\x01\x02\x03\x08\x09\x0a\x0b\x0f\x10\x11\x12\x13\x18\x19\x1a\x1b\x20\x21\x22\x23\x28\x29\x2a\x2b\x30\x31\x32\x33\x38\x39\x3a\x3b\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x6b\x80\x83\xf6"
BIG_OPCODES = b"\x69\x81\x6b\x80\x83\xc0\xc1\xf6"
ANTI_DISASM_EXTRA_BYTE = 0xF4
SINGLE_BYTE_OPCODE_SET = set(SINGLE_BYTE_OPCODES)
MED_OPCODE_SET = set(MED_OPCODES)
BIG_OPCODE_SET = set(BIG_OPCODES)
# fmt: on


class Memory(io.BytesIO):
    class Address(int):
        def __new__(cls, value, is_absolute=True):
            # Create an int subclass that also knows whether it's absolute.
            obj = int.__new__(cls, value)
            obj.is_absolute = is_absolute
            return obj

        def to_absolute(self, memory):
            """
            Convert to an absolute address using the memory's base.
            """
            if self.is_absolute:
                return self
            return Memory.Address(self + memory.base, is_absolute=True)

        def to_relative(self, memory):
            """
            Convert to a relative address (i.e. an index into the memory buffer)
            based on the memory's base.
            """
            if not self.is_absolute:
                return self
            return Memory.Address(self - memory.base, is_absolute=False)

        def __repr__(self):
            kind = "Abs" if self.is_absolute else "Rel"
            return f"<Memory.Address {kind}: {int(self):#010X}>"

    def __init__(self, data, base=0, dtype="B"):
        """
        Initialize the Memory instance from a bytes-like buffer or a single byte integer.

        :param data: A bytes-like object, an array.array instance, or a single integer.
        :param base: The base (starting) address for rebasing indexing.
        """
        # Convert incoming data to an array of unsigned bytes if necessary.
        if isinstance(data, array.array):
            self._buffer = data
        elif isinstance(data, int):
            # Handle single integer byte value
            if 0 <= data <= 255:
                self._buffer = array.array(dtype, [data])
            else:
                raise ValueError("Integer data must be a valid byte value (0-255)")
        else:
            # Assume bytes-like object
            self._buffer = array.array(dtype, data)

        # Initialize file-like behavior using BytesIO.
        super().__init__(self._buffer.tobytes())
        self.base = base

    @classmethod
    def from_buffer(cls, buffer, base=0):
        """
        Convenience method for constructing a Memory instance.
        For example:

            mem = Memory.from_buffer(ida_bytes.get_bytes(text_seg.start_ea, text_seg.size()),
                                     base=text_seg.start_ea)

        This ensures that mem[0] corresponds to the byte at text_seg.start_ea.
        """
        return cls(buffer, base)

    @classmethod
    def from_ida_range(cls, start_ea: int, end_ea: int):
        """Creates a Memory object by reading bytes directly from IDA."""
        size = end_ea - start_ea
        if size <= 0:
            logger.error(
                f"Invalid IDA range for Memory: start=0x{start_ea:X}, end=0x{end_ea:X}"
            )
            ida_bytes_data = b""
        else:
            logger.debug(
                f"Reading {size} bytes from IDA: 0x{start_ea:X} to 0x{end_ea:X}"
            )
            ida_bytes_data = ida_bytes.get_bytes(start_ea, size)
            if ida_bytes_data is None:
                logger.error(
                    f"Failed to read memory from IDA: 0x{start_ea:X} to 0x{end_ea:X}"
                )
                ida_bytes_data = b""

        instance = cls(ida_bytes_data, base=start_ea)
        return instance

    @classmethod
    def from_ida_segment(cls, seg: ida_segment.segment_t):
        """Creates a Memory object from an IDA segment."""
        if not seg:
            logger.error("Invalid segment provided to Memory.from_ida_segment")
            return cls(b"", base=0)  # Return empty memory object
        return cls.from_ida_range(seg.start_ea, seg.end_ea)

    def __bytes__(self):
        return self._buffer.tobytes()

    @property
    def view(self):
        """Return a memoryview of the underlying array."""
        return memoryview(self._buffer)

    def finditer(self, pattern, flags=0):
        """
        Find all non-overlapping matches of pattern in string.
        """
        if isinstance(pattern, re.Pattern):
            return pattern.finditer(self.view)
        return re.compile(pattern, flags).finditer(self.view)

    def findall(self, pattern, flags=0):
        """
        Find all non-overlapping matches of pattern in string.
        """
        return list(self.finditer(pattern, flags))

    def search(self, pattern, flags=0):
        """
        Scan through string looking for the first location where the regular expression pattern produces a match, and return a corresponding Match. Return None if no position in the string matches the pattern; note that this is different from finding a zero-length match at some point in the string.
        """
        if isinstance(pattern, re.Pattern):
            return pattern.search(self.view)
        return re.compile(pattern, flags).search(self.view)

    def match(self, pattern, flags=0):
        """
        Match the regular expression pattern to the string.
        """
        if isinstance(pattern, re.Pattern):
            return pattern.match(self.view)
        return re.compile(pattern, flags).match(self.view)

    def __getitem__(self, index):
        """
        Support indexing (and slicing) where:
          - A relative index (e.g. mem[0]) returns the first byte as an integer.
          - An absolute address (>= self.base) is automatically rebased.
          - Slicing returns a new Memory object.
        """
        if isinstance(index, int):
            # Adjust if the index is given as an absolute address.
            if self.base and index >= self.base:
                index -= self.base
            if index < 0 or index >= len(self._buffer):
                raise IndexError("Memory index out of range")
            return self._buffer[index]

        elif isinstance(index, slice):
            start, stop, step = index.start, index.stop, index.step
            if start is not None and self.base and start >= self.base:
                start -= self.base
            if stop is not None and self.base and stop >= self.base:
                stop -= self.base
            return Memory(self._buffer[slice(start, stop, step)])

        else:
            raise TypeError("Index must be an int or a slice")

    def __len__(self):
        """Return the total size of the underlying buffer."""
        return len(self._buffer)

    def find(self, pattern, start=0, end=None, absolute=True):
        """
        Search for a byte sequence within the memory.

        :param pattern: The byte pattern to search for. Accepts bytes, bytearray, list of ints, or array.array.
        :param start: The start index. If given as an absolute address (>= self.base), it is rebased.
        :param end: The end index. If given as an absolute address, it is rebased. If None, searches to the end.
        :param absolute: If True, returns a Memory.Address as an absolute address; otherwise, as a relative offset.
        :return: A Memory.Address for the location of the pattern or -1 if not found.
        """
        data = self._buffer.tobytes()

        if isinstance(pattern, (bytes, bytearray)):
            pat = pattern
        elif isinstance(pattern, array.array):
            pat = pattern.tobytes()
        elif isinstance(pattern, list):
            pat = bytes(pattern)
        else:
            raise TypeError(
                "Pattern must be bytes, bytearray, list of ints, or array.array."
            )

        if start is None:
            start = 0
        elif self.base and start >= self.base:
            start -= self.base
        if end is None:
            end = len(self._buffer)
        elif self.base and end >= self.base:
            end -= self.base

        pos = data.find(pat, start, end)
        if pos == -1:
            return Memory.Address(-1, is_absolute=absolute)
        addr = pos + (self.base if absolute else 0)
        return Memory.Address(addr, is_absolute=absolute)

    def rebase(self, new_base):
        """
        Update the base (absolute) address of this Memory.
        """
        self.base = new_base

    def sliding_window(self, window_size):
        """
        Yield all contiguous sub-sections (windows) of the given window_size.

        Example:
            for window in mem.sliding_window(4):
                print(list(window))
        """
        total = len(self._buffer)
        for index in range(total - window_size + 1):
            yield self._buffer[index : index + window_size]

    def hexdump(self, data=None, addr=None, bytes_per_line=16, joined=True):
        """
        Create a hexdump for display of the given data.

        :param data: Data to dump. If None, dumps the entire memory.
        :param addr: Starting address for display. If None, uses self.base.
        :param bytes_per_line: Number of bytes per line.
        :param joined: If True, returns a single string; otherwise, a list of lines.
        :return: A hexdump as a string or list of lines.
        """
        if data is None:
            data = self._buffer.tobytes()
        if addr is None:
            addr = self.base

        result = []
        for i in range(0, len(data), bytes_per_line):
            chunk = data[i : i + bytes_per_line]
            hex_values = " ".join(f"{b:02X}" for b in chunk)
            ascii_values = "".join(chr(b) if 32 <= b <= 126 else "." for b in chunk)
            result.append(
                f"{addr + i:08X}: {hex_values.ljust(bytes_per_line * 3)} {ascii_values}"
            )
        return "\n".join(result) if joined else result

    def hex(
        self, sep: str | bytes = ..., bytes_per_sep: typing.SupportsIndex = 1
    ) -> str:
        b = self._buffer.tobytes()
        if sep is Ellipsis:
            return b.hex()
        else:
            return b.hex(sep, bytes_per_sep)

    def sublist(self, start, end):
        """
        Return a new Memory instance that represents a sub-range of this Memory.

        The start and end parameters may be provided as absolute addresses (>= self.base)
        or as relative offsets. The new Memory instance will have its base adjusted accordingly.

        Example:
            sub_mem = mem.sublist(0x140001100, 0x140001200)
            # or using relative offsets:
            sub_mem = mem.sublist(0x100, 0x200)
        """
        # Convert absolute addresses to relative indexes if necessary.
        if isinstance(start, int) and start >= self.base:
            rel_start = start - self.base
        else:
            rel_start = start

        if isinstance(end, int) and end >= self.base:
            rel_end = end - self.base
        else:
            rel_end = end

        if rel_start < 0 or rel_end > len(self._buffer) or rel_start > rel_end:
            raise ValueError("sublist range out of bounds")

        # Depending on the type of self._buffer, slicing may return a new object.
        # Note: Slicing an array.array returns a new copy. If a shared view is desired,
        # consider using a memoryview instead.
        new_data = self._buffer[rel_start:rel_end]
        new_base = self.base + rel_start
        return Memory(new_data, base=new_base)

    def _get_bytes_or_buffer(self, other):
        """helper method to consistently extract an array.array from other, whether it's another Memory instance, bytes, bytearray, or array.array.

        It raises a TypeError for unsupported types."""
        if isinstance(other, Memory):
            return other._buffer
        elif isinstance(other, (bytes, bytearray)):
            return array.array(self._buffer.typecode, other)
        elif isinstance(other, array.array):
            if other.typecode != self._buffer.typecode:
                raise TypeError(
                    f"Cannot concatenate arrays with different typecodes ('{self._buffer.typecode}' and '{other.typecode}')"
                )
            return other
        else:
            raise TypeError(
                f"Unsupported operand type for +: 'Memory' and '{type(other).__name__}'"
            )

    def __add__(self, other):
        """Handle self + other."""
        other_buffer = self._get_bytes_or_buffer(other)
        new_buffer = self._buffer + other_buffer
        # Create new Memory object, preserving self.base
        return Memory(new_buffer, base=self.base)

    def __radd__(self, other):
        """Handle other + self."""
        other_buffer = self._get_bytes_or_buffer(other)
        new_buffer = other_buffer + self._buffer
        # Decide on base: if other is Memory, use its base?
        # For now, let's default to using self.base, but this could be debated.
        # If other is Memory, maybe other.base is more logical?
        # Let's stick with self.base for consistency unless a use case demands otherwise.
        new_base = (
            other.base if isinstance(other, Memory) else self.base
        )  # Use other's base if it's Memory
        return Memory(new_buffer, base=new_base)

    def __iadd__(self, other):
        """Handle self += other."""
        other_buffer = self._get_bytes_or_buffer(other)
        self._buffer.extend(other_buffer)
        # Re-initialize the BytesIO part to reflect the change
        # This resets the stream position to 0.
        current_pos = self.tell()
        super().__init__(self._buffer.tobytes())
        self.seek(
            current_pos
        )  # Try to restore position, might not be perfect if append changed size past pos
        return self

    def __len__(self):
        """Return the total size of the underlying buffer."""
        return len(self._buffer)


class PatchManager:
    """Manages deferred patch operations."""

    class Mode(Enum):
        PATCH = auto()  # Use ida_bytes.patch_bytes
        PUT = auto()  # Use ida_bytes.put_bytes

    def __init__(
        self,
        patch_mode: Mode = Mode.PATCH,
        dry_run: bool = False,
        auto_clear: bool = True,
    ):
        self.dry_run = dry_run
        self.patch_mode = patch_mode
        self.pending_patches: list[DeferredPatchOp] = []
        self.auto_clear = auto_clear
        logger.info(
            f"PatchManager initialized (dry_run={self.dry_run}, mode={self.patch_mode.name})"
        )

    def add_patch(self, address: int, byte_values: bytes):
        """Creates and queues a DeferredPatchOp."""
        op = DeferredPatchOp(address, byte_values, self.patch_mode)
        self.pending_patches.append(op)
        logger.debug(f"Queued patch operation: {op}")

    def apply_all(self, dry_run_override: bool | None = None) -> bool:
        """Applies all queued patch operations."""
        logger.info(f"Applying {len(self)} queued patches...")
        success_count = 0
        fail_count = 0

        if dry_run_override is None:
            # None is a sentinel value here that represents "use the default"
            dry_run_override = self.dry_run

        for op in self.pending_patches:
            if op.apply(dry_run_override):
                success_count += 1
            else:
                fail_count += 1

        logger.info(
            f"Patch application complete. Success: {success_count}, Failed: {fail_count}"
        )
        if self.auto_clear:
            self.pending_patches.clear()  # Clear the list after applying
        return fail_count == 0  # Return True if all patches were applied successfully

    def __len__(self) -> int:
        return len(self.pending_patches)


@dataclass(repr=False)
class DeferredPatchOp:
    """Class to store patch operations that will be applied later."""

    address: int
    byte_values: bytes
    mode: PatchManager.Mode
    dry_run: bool = False

    @classmethod
    def patch(cls, address: int, byte_values: bytes, dry_run: bool = False):
        return cls(address, byte_values, PatchManager.Mode.PATCH, dry_run)

    @classmethod
    def put(cls, address: int, byte_values: bytes, dry_run: bool = False):
        return cls(address, byte_values, PatchManager.Mode.PUT, dry_run)

    def apply(self, dry_run_override: bool = False) -> bool:
        """Apply the patch operation using either patch_bytes or put_bytes based on mode."""
        is_dry_run = dry_run_override or self.dry_run
        logger.info(
            "[*] %sPatching decrypted chunk %s at 0x%X (size: %d)",
            "(Dry Run) " if is_dry_run else "",
            "revertably" if self.mode == PatchManager.Mode.PATCH else "destructively",
            self.address,
            len(self.byte_values),
        )
        success = True
        if is_dry_run:
            return success

        func = (
            idaapi.put_bytes
            if self.mode == PatchManager.Mode.PUT
            else idaapi.patch_bytes
        )
        try:
            func(self.address, self.byte_values)
        except Exception as e:
            logger.error(f"Failed to apply patch {self}: {e}")
            success = False
        return success

    def __str__(self):
        """String representation with hex formatting."""
        dry_run_str = " (dry run)" if self.dry_run else ""
        return f"{self.__class__.__name__}({len(self.byte_values)} bytes, mode={self.mode.name}{dry_run_str} @ address=0x{self.address:X})"

    __repr__ = __str__


class SegmentType(Enum):
    STAGE1_SINGLE = auto()
    STAGE1_MULTIPLE = auto()
    JUNK = auto()
    BIG_INSTRUCTION = auto()


@dataclass
class MatchSegment:
    start: int
    length: int
    description: str
    matched_bytes: Memory
    segment_type: SegmentType
    matched_groups: typing.Dict[str, bytes] | None = None


class MatchChain:
    def __init__(self, base_address: int, segments: typing.List[MatchSegment] = None):
        self.base_address = base_address
        self.segments = segments or []

    def add_segment(self, segment: MatchSegment):
        self.segments.append(segment)

    def overall_start(self) -> int:
        return self.segments[0].start + self.base_address if self.segments else 0

    def overall_length(self) -> int:
        if not self.segments:
            return 0
        first = self.segments[0]
        last = self.segments[-1]
        return (last.start + last.length) - first.start

    def overall_matched_bytes(self) -> bytes:
        return b"".join(seg.matched_bytes.view for seg in self.segments)

    def append_junk(
        self, junk_start: int, junk_len: int, junk_desc: str, junk_bytes: Memory
    ):
        seg = MatchSegment(
            start=junk_start,
            length=junk_len,
            description=junk_desc,
            matched_bytes=junk_bytes,
            segment_type=SegmentType.JUNK,
        )
        self.add_segment(seg)

    @property
    def description(self) -> str:
        desc = []
        for idx, seg in enumerate(self.segments):
            if idx == 0:
                desc.append(f"{seg.description}")
            else:
                desc.append(f" -> {seg.description}")
        return "".join(desc)

    def update_description(self, new_desc: str):
        if self.segments:
            self.segments[0].description = new_desc

    # New properties for junk analysis
    @property
    def stage1_type(self) -> SegmentType:
        return self.segments[0].segment_type

    @property
    def junk_segments(self) -> list:
        """
        Returns a list of segments considered as junk based on their segment_type.
        """
        return [seg for seg in self.segments if seg.segment_type == SegmentType.JUNK]

    @property
    def junk_starts_at(self) -> typing.Optional[int]:
        """
        Returns the starting address of the junk portion.
        This is computed as base_address + the offset of the first junk segment.
        If no junk segments exist, returns None.
        """
        js = self.junk_segments
        if js:
            return self.base_address + js[0].start
        return None

    @property
    def junk_length(self) -> int:
        """
        Returns the total length of the junk portion.
        This is computed as the difference between the end (start + length) of the last junk segment
        and the start of the first junk segment.
        If there are no junk segments, returns 0.
        """
        js = self.junk_segments
        if not js:
            return 0
        first = js[0]
        last = js[-1]
        return (last.start + last.length) - first.start

    def __lt__(self, other):
        return self.overall_start() < other.overall_start()

    def __repr__(self):
        r = [
            f"{self.description.rjust(32, ' ')} @ 0x{self.overall_start():X} - "
            f"{self.overall_matched_bytes().hex()[:16]}"
            f"{'...' if self.overall_length() > 16 else ''}",
            "  |",
        ]
        for seg in self.segments:
            _grps = f"{' - ' + str(seg.matched_groups) if seg.matched_groups else ''}"
            r.append(
                f"  |_ {seg.description} @ 0x{self.base_address + seg.start:X} - {seg.matched_bytes.hex()}{_grps}"
            )
        return "\n".join(r)


class MatchChains:
    def __init__(self):
        self.chains = []

    def add_chain(self, chain: MatchChain):
        self.chains.append(chain)

    def __repr__(self):
        _the_repr = []
        for chain in self.chains:
            _the_repr.append(
                f"{chain.description.rjust(32, ' ')} @ 0x{chain.overall_start():X} - "
                f"{chain.overall_matched_bytes().hex()[:16]}"
                f"{'...' if chain.overall_length() > 16 else ''}"
            )
        return "\n".join(_the_repr)

    def __iter__(self):
        yield from self.chains

    def sort(self):
        self.chains.sort(key=lambda x: x.overall_start())

    def __len__(self):
        return len(self.chains)


@dataclasses.dataclass
class BasicDecodedInstruction:
    """Holds standardized information about a decoded instruction."""

    address: int
    size: int
    is_jump: bool = False
    jump_target: typing.Optional[int] = None
    is_nop: bool = False


class InstructionDecoder(typing.Protocol):
    """Protocol defining the expected signature for decoder functions."""

    def decode(
        self, ea: int, mem_bytes_at_ea: bytes
    ) -> typing.Optional[BasicDecodedInstruction]:
        """
        Decodes the instruction at virtual address 'ea' using the provided memory bytes.

        Args:
            ea: The virtual address of the instruction to decode.
            mem_bytes_at_ea: A bytes object containing memory starting from 'ea'.
                             The implementation should only consume the bytes
                             needed for the single instruction at 'ea'.

        Returns:
            An InstructionInfo object if decoding is successful, otherwise None.
        """
        ...


class IdaInstructionDecoder(InstructionDecoder):

    def decode(
        self, ea: int, mem_bytes_at_ea: bytes
    ) -> typing.Optional[BasicDecodedInstruction]:
        """
        Decodes instruction at ea using IDA's disassembler.
        Ignores mem_bytes_at_ea, uses IDA's database.
        Conforms to DecoderProtocol.
        """
        insn = ida_ua.insn_t()
        length = ida_ua.decode_insn(insn, ea)

        if length == 0:
            logger.debug(f"IDA decode failed: Zero length instruction at 0x{ea:X}.")
            return None

        decoded = BasicDecodedInstruction(address=ea, size=length)
        if insn.itype == ida_allins.NN_nop:
            decoded.is_nop = True

        elif insn.itype in ALL_JUMPS and insn.Op1.type == ida_ua.o_near:
            decoded.is_jump = True
            decoded.jump_target = insn.Op1.addr
        return decoded


class CapstoneInstructionDecoder(InstructionDecoder):

    def decode(
        self, ea: int, mem_bytes_at_ea: bytes
    ) -> typing.Optional[BasicDecodedInstruction]:
        """
        Decodes instruction at ea using IDA's disassembler.
        Ignores mem_bytes_at_ea, uses IDA's database.
        Conforms to DecoderProtocol.
        """
        # Decode using Capstone
        try:
            # Use list comprehension and next to get the first instruction or None
            insn = next(md.disasm(mem_bytes_at_ea, ea, count=1), None)
        except capstone.CsError as e:
            logger.error(f"Capstone decoding error at 0x{ea:X}: {e}")
            return None

        if insn is None:
            return None

        decoded = BasicDecodedInstruction(address=ea, size=insn.size)
        if insn.id == capstone.x86.X86_INS_NOP:
            decoded.is_nop = True
        elif capstone.CS_GRP_JUMP in insn.groups:
            if (
                len(insn.operands) > 0
                and insn.operands[0].type == capstone.x86.X86_OP_IMM
            ):
                decoded.is_jump = True
                decoded.jump_target = insn.operands[0].imm
        return decoded


@dataclass
class JumpTargetAnalyzer:
    # Input parameters for processing jumps.
    match_bytes: bytes  # The bytes in which we're matching jump instructions.
    match_start: int  # The address where match_bytes starts.
    block_end: int  # End address of the allowed region.
    start_ea: int  # Base address of the memory block (used for bounds checking).

    # Define jump patterns to search within match_bytes.
    jump_patterns: list = field(
        init=False,
        default_factory=lambda: [
            rb"\x90*[\xEB\xE9].",  # JMP rel8
            rb"\x90*[\x70-\x7F].",  # Jcc rel8
        ],
    )
    # Internal structures.
    jump_targets: collections.Counter = field(
        init=False, default_factory=collections.Counter
    )
    jump_details: list = field(
        init=False, default_factory=list
    )  # List of (jump_ea, final_target, stage1_type)
    insertion_order: dict = field(
        init=False, default_factory=dict
    )  # final_target -> order index
    target_type: dict = field(
        init=False, default_factory=dict
    )  # final_target -> stage1_type

    def follow_jump_chain(
        self,
        mem: Memory,  # Expect a Memory object
        current_ea: int,
        match_end: int,
        decoder: InstructionDecoder,
        visited: set = None,
        depth: int = 0,
    ) -> typing.Optional[int]:
        """
        Follow a chain of 2-byte jumps starting from current_ea using the provided decoder.

        Args:
            mem: Memory object containing the relevant byte data. Its 'base' attribute
                 defines the absolute address corresponding to the start of its buffer.
            current_ea: The absolute starting virtual address for tracing.
            match_end: The absolute end address (exclusive) of the 'stage1' area.
            decoder: A function conforming to DecoderProtocol used for disassembly.
            visited: Set of visited addresses to prevent loops (internal use).
            depth: Recursion depth for logging (internal use).

        Returns:
            The absolute virtual address where the jump chain ends, or None.
        """
        indent = "  " * depth + "|_ "
        if visited is None:
            visited = set()

        # Get an efficient view of the memory buffer
        mem_view = mem.view
        mem_start_ea = mem.base  # Absolute start address of the buffer
        mem_len = len(mem_view)
        mem_end_ea = mem_start_ea + mem_len  # Absolute end address (exclusive)

        if current_ea in visited:
            logger.debug(
                f"{indent}Jump chain stopped: Already visited 0x{current_ea:X}"
            )
            return None
        # Check if start address is within the bounds defined by the Memory object
        if not (mem_start_ea <= current_ea < mem_end_ea):
            logger.debug(
                f"{indent}Jump chain stopped: Start address 0x{current_ea:X} is outside Memory bounds [0x{mem_start_ea:X}, 0x{mem_end_ea:X})"
            )
            return None

        visited.add(current_ea)

        trace_ea = current_ea
        while True:
            # Check if the current tracing address is still within the Memory bounds
            if not (mem_start_ea <= trace_ea < mem_end_ea):
                logger.debug(
                    f"{indent}Stopping trace: Address 0x{trace_ea:X} is outside Memory bounds [0x{mem_start_ea:X}, 0x{mem_end_ea:X}). Returning last valid start: 0x{current_ea:X}"
                )
                return current_ea  # Return the start address of the sequence that led out of bounds

            decoded_insn = None
            # Calculate offset relative to the start of the Memory object's buffer
            offset = trace_ea - mem_start_ea
            # We already know offset is >= 0 because trace_ea >= mem_start_ea
            # We need to ensure we have enough bytes left for *potential* instructions

            # Get bytes starting from the offset using the memoryview slice
            # Convert the slice to bytes for the decoder interface
            bytes_for_decoder = mem_view[offset:].tobytes()
            if (
                not bytes_for_decoder
            ):  # Should not happen if bounds check is correct, but defensive check
                logger.warning(
                    f"{indent}No bytes available for decoding at offset {offset} (address 0x{trace_ea:X}). Stopping trace."
                )
                return current_ea

            try:
                # Call the passed-in decoder function
                decoded_insn = decoder.decode(trace_ea, bytes_for_decoder)
            except Exception as e:
                logger.error(
                    f"{indent}Decoder function raised exception at 0x{trace_ea:X}: {e}"
                )
                decoded_insn = None  # Treat as decode failure

            # If decoding failed or decoder returned None
            if not decoded_insn:
                logger.debug(
                    f"{indent}Failed to decode instruction at 0x{trace_ea:X}. Stopping trace. Returning start: 0x{current_ea:X}"
                )
                return current_ea  # Return start of the sequence

            # --- Process the decoded instruction ---
            if decoded_insn.is_nop:
                logger.debug(
                    f"{indent}NOP found at 0x{trace_ea:X} (size {decoded_insn.size}). Skipping."
                )
                trace_ea += decoded_insn.size
                continue  # Continue the while loop to the next instruction

            if not decoded_insn.is_jump or decoded_insn.size != 2:
                logger.debug(
                    f"{indent}Chain stopped at 0x{trace_ea:X}: Instruction is not a 2-byte jump. Returning start: 0x{current_ea:X}"
                )
                return current_ea  # Return the start address of the sequence that ended

            # --- We have a 2-byte jump ---
            target = decoded_insn.jump_target  # This is an absolute address
            logger.debug(
                f"{indent}  -> Found 2-byte jump at 0x{trace_ea:X} targeting 0x{target:X}"
            )

            # --- Decide action based on the jump target (using absolute addresses) ---
            # 1. Target is within the 'followable' range [match_start, match_end + 6)
            if self.match_start <= target < match_end + 6:
                logger.debug(
                    f"{indent}Following jump from 0x{trace_ea:X} to 0x{target:X} (recursive call)"
                )
                # Pass the same Memory object and decoder down recursively
                return self.follow_jump_chain(
                    mem, target, match_end, decoder, visited, depth + 1
                )

            # 2. Target lands exactly at the potential start of the next stage
            elif target == match_end + 6:
                logger.debug(
                    f"{indent}Jump chain ends: Reached potential next stage start 0x{target:X}"
                )
                return target  # Return the exact target address

            # 3. Target is within the overall Memory block, but *before* match_start.
            elif mem_start_ea <= target < self.match_start:
                logger.debug(
                    f"{indent}Jump chain ends: Target 0x{target:X} is within Memory bounds [{mem_start_ea:X},{mem_end_ea:X}) but outside followable range [{self.match_start:X}, {match_end + 6:X}). Returning target."
                )
                return target  # Return the target address itself

            # 4. Target is out of the overall Memory bounds or otherwise unexpected.
            else:
                logger.debug(
                    f"{indent}Jump chain stopped: Target 0x{target:X} is outside allowed ranges. Returning start address 0x{current_ea:X}"
                )
                return current_ea  # Return the start address of the sequence containing the invalid jump

    def process(self, mem, chain):
        """
        Process each jump match in match_bytes.
        'chain' is expected to have attributes:
          - junk_length: int
          - stage1_type: SegmentType
        """
        decoder = CapstoneInstructionDecoder()
        match_end = chain.overall_start() + chain.overall_length()
        logger.debug(
            f"Processing jumps for chain @ 0x{chain.overall_start():X}, match_end=0x{match_end:X}"
        )
        for jump_match in re.finditer(
            rb"[\xEB\x70-\x7F].", self.match_bytes, re.DOTALL
        ):
            jump_offset = jump_match.start()
            jump_ea = self.match_start + jump_offset
            # offset = struct.unpack("<b", jump_match.group()[-1:])[0]
            # Compute the final target assuming a 2-byte instruction.
            # final_target = jump_ea + 2 + offset
            final_target = self.follow_jump_chain(mem, jump_ea, match_end, decoder)
            if not final_target:
                logger.debug(
                    f"  Skipping jump at 0x{jump_ea:X}: Invalid final target 0x{final_target if final_target else 0:X}"
                )
                continue

            # Adjusted condition: Target must be *after* the match end and within 6 bytes
            if abs(final_target - match_end) > 6:
                logger.debug(
                    f"  Skipping jump at 0x{jump_ea:X}: Final target 0x{final_target:X} not within [(0x{match_end - 6:X}, 0x{match_end:X}) or (0x{match_end:X}, 0x{match_end + 6:X}]"
                )
                continue
            self.jump_targets[final_target] += 1
            # Record the insertion order and the stage1_type on the first occurrence.
            if final_target not in self.insertion_order:
                self.insertion_order[final_target] = len(self.insertion_order)
                self.target_type[final_target] = chain.stage1_type
            self.jump_details.append((jump_ea, final_target, chain.stage1_type))
            logger.debug(
                f"  Found {jump_match.group().hex()} @ 0x{jump_ea:X} targeting 0x{final_target:X}"
            )
        return self

    def sorted_targets(self):
        """
        Return a sorted list of (final_target, count) tuples.

        Sorting behavior depends on the stage1_type:
         - For STAGE1_MULTIPLE: sort by count descending, then by final_target descending.
         - For STAGE1_SINGLE: sort by count descending, then by the order in which the target was first seen.
           (That is, when counts are equal, the first inserted target wins.)
         - For other types, default to (count, final_target) descending.
        """
        results = []
        for target, count in self.jump_targets.items():
            stype = self.target_type.get(target)
            order = self.insertion_order.get(target, 0)
            if stype == SegmentType.STAGE1_SINGLE:
                key_tuple = (
                    count,
                    -order,
                )  # higher count, then lower insertion order (i.e. first seen)
            else:
                key_tuple = (count, target)  # higher count, then higher address
            results.append((target, key_tuple))
        results.sort(key=lambda x: x[1], reverse=True)
        # Return a list of (final_target, count) tuples.
        return [(target, self.jump_targets[target]) for target, _ in results]

    def __iter__(self):
        """
        Iterate over the most likely targets.
        For each candidate, if a jump exists whose starting address equals candidate + 1,
        yield its final target instead.
        """
        for candidate, count in self.sorted_targets():
            final_candidate = candidate
            for jump_ea, target, stype in self.jump_details:
                if jump_ea == candidate + 1:
                    final_candidate = target
                    break
            yield final_candidate


def find_stage1(mem, ea: int, end_ea: int) -> MatchChains:
    logger.info(
        "Searching for stage1 patterns from 0x{:X} to 0x{:X}".format(ea, end_ea)
    )

    # Combine all patterns, keeping your original format
    patterns = [
        (
            MULTI_PART_PATTERNS,
            "Multi-Part Conditional Jumps",
            SegmentType.STAGE1_MULTIPLE,
        ),
        (
            SINGLE_PART_PATTERNS,
            "Single-Part Conditional Jumps",
            SegmentType.STAGE1_SINGLE,
        ),
    ]

    all_chains = MatchChains()
    for pattern_group, desc, segment_type in patterns:
        if not isinstance(pattern_group, list):
            pattern_group = [pattern_group]

        for pattern in pattern_group:
            for m in mem.finditer(pattern.compile()):
                match_len = m.end() - m.start()
                matched_bytes = mem[m.start() : m.end()]
                matched_groups = {
                    k: f"{v.hex()}" for k, v in m.groupdict().items() if k != "padding"
                }
                if "jump" in matched_groups:
                    offset = struct.unpack("<b", matched_bytes[-1:].view)[0]
                    target = ea + m.start() + match_len + offset
                    matched_groups["target"] = format_addr(target)
                elif "first_jump" in matched_groups:
                    offset = struct.unpack("<b", matched_bytes[1:2].view)[0]
                    matched_groups["first_target"] = format_addr(
                        ea + m.start() + 2 + offset
                    )
                    offset = struct.unpack("<b", matched_bytes[-1:].view)[0]
                    target = ea + m.start() + match_len + offset
                    matched_groups["second_target"] = format_addr(target)
                all_chains.add_chain(
                    MatchChain(
                        base_address=ea,
                        segments=[
                            MatchSegment(
                                start=m.start(),
                                length=match_len,
                                description=desc,
                                matched_bytes=matched_bytes,
                                segment_type=segment_type,
                                matched_groups=matched_groups,
                            )
                        ],
                    )
                )
    all_chains.sort()
    logger.info(f"Phase 1: Found {len(all_chains)} stage1 chains")
    return all_chains


# Function to find junk instructions after stage1 matches
def find_junk_instructions_after_stage1(
    mem: Memory, stage1_chains: MatchChains, start_ea: int, func_end: int
) -> MatchChains:
    """
    - Register-based operations (0-57): ~58% chance.
    - RDTSC (58-60): ~3% chance.
    - PUSH imm32 (61-62): ~2% chance.
    - PUSH imm8 (63-65): ~3% chance.
    - Single-byte instructions (66-75): ~10% chance.
    - Conditional jumps with 8-bit offset (76-80): ~5% chance.
    - Conditional jumps with 32-bit offset (81-90): ~10% chance.
    - CALL instruction (91-99): ~9% chance.
    """
    logger.info(
        f"Phase 2: Checking for junk instructions immediately following {len(stage1_chains)} stage1 matches"
    )

    for chain in ida_helpers.ida_tguidm(stage1_chains):
        stage1_start = chain.overall_start()
        stage1_len = chain.overall_length()
        stage1_desc = chain.segments[0].description
        stage1_bytes = chain.overall_matched_bytes()

        # Calculate the position immediately after the Stage1 match in mem_results
        current_pos = stage1_start + stage1_len - start_ea
        if current_pos >= len(mem):
            print(f"No room for junk after {stage1_desc} @ 0x{stage1_start:X}")
            continue

        # Extract the buffer after the Stage1 match
        post_stage1_buffer = mem[current_pos:]
        total_junk_len = 0

        logger.debug(
            f"Searching for junk instruction sequence after {stage1_desc} at 0x{stage1_start:X} "
            f"(starting from 0x{stage1_start + stage1_len:X})"
        )

        # Iterate while there's enough space for another junk instruction (> 6 bytes)
        while len(post_stage1_buffer) > 6:
            junk_found = False
            for junk_pattern in JUNK_PATTERNS:
                match = post_stage1_buffer.match(junk_pattern.compile())
                if match:
                    junk_len = match.end() - match.start()
                    junk_bytes = post_stage1_buffer[:junk_len]
                    chain.append_junk(
                        junk_start=current_pos + total_junk_len,
                        junk_len=junk_len,
                        junk_desc=junk_pattern.description,
                        junk_bytes=junk_bytes,
                    )
                    total_junk_len += junk_len
                    post_stage1_buffer = post_stage1_buffer[junk_len:]
                    junk_found = True
                    logger.debug(
                        f"  Found {junk_pattern.description} @ 0x{stage1_start + stage1_len + total_junk_len - junk_len:X} "
                        f"({junk_len} bytes: {junk_bytes.hex()})"
                    )
                    break  # Move to the next portion of the buffer

            if not junk_found:
                logger.debug(
                    f"  No more junk instructions match with {len(post_stage1_buffer)} bytes remaining"
                )
                break  # Exit if no junk instruction matches
    stage1_chains.sort()
    return stage1_chains


def find_big_instruction(buffer_bytes: bytes, is_x64: bool = False) -> dict:
    """
    Find the 'big instruction' in a 6-byte buffer, checking specific positions from the end.
    According to the constraints, the buffer will always be exactly 6 bytes.

    Args:
        buffer_bytes (bytes): The 6-byte buffer to analyze.
        is_x64 (bool): Whether to check for REX prefixes (x64 mode).

    Returns:
        dict: A dictionary containing information about the found instruction.
    """
    assert len(buffer_bytes) == 6, "Buffer must be exactly 6 bytes"

    # Function to check if a byte is a valid REX prefix (0x40-0x4F)
    def is_rex_prefix(byte):
        return 0x40 <= byte <= 0x4F

    # Function to check if a byte is a valid ModR/M byte (0x80-0xBF)
    def is_valid_modrm(byte):
        return 0x80 <= byte <= 0xBF

    # Ensure we have a 6-byte buffer
    if len(buffer_bytes) != 6:
        return {
            "type": None,
            "name": "Invalid buffer size",
            "instruction": [],
            "position": -1,
            "junk_before": buffer_bytes,
            "junk_after": [],
        }

    # 1. First check for 3-byte instructions in x64 mode (highest priority)
    if is_x64:
        # Check all possible positions for 3-byte instructions (REX + opcode + ModR/M)
        for pos in range(4):  # Start positions 0, 1, 2, 3
            if pos + 2 >= len(buffer_bytes):
                continue

            rex = buffer_bytes[pos]
            opcode = buffer_bytes[pos + 1]
            modrm = buffer_bytes[pos + 2]

            if is_rex_prefix(rex):
                # Check if it forms a valid 3-byte instruction
                if opcode in MED_OPCODE_SET and is_valid_modrm(modrm):
                    # Get junk bytes at the end (based on position)
                    junk_after = buffer_bytes[pos + 3 :]

                    # Verify junk bytes constraint for 3-byte instructions
                    expected_junk_bytes = max(0, 3 - pos)
                    if len(junk_after) == expected_junk_bytes:
                        return {
                            "type": "3-byte",
                            "name": "REX + Two-byte Med instruction",
                            "instruction": [rex, opcode, modrm],
                            "position": pos,
                            "junk_before": buffer_bytes[:pos],
                            "junk_after": junk_after,
                        }

                elif opcode in BIG_OPCODE_SET and is_valid_modrm(modrm):
                    # Get junk bytes at the end (based on position)
                    junk_after = buffer_bytes[pos + 3 :]

                    # Verify junk bytes constraint for 3-byte instructions
                    expected_junk_bytes = max(0, 3 - pos)
                    if len(junk_after) == expected_junk_bytes:
                        return {
                            "type": "3-byte",
                            "name": "REX + Two-byte Big instruction",
                            "instruction": [rex, opcode, modrm],
                            "position": pos,
                            "junk_before": buffer_bytes[:pos],
                            "junk_after": junk_after,
                        }

    # 2. Next check for 2-byte instructions
    for pos in range(5):  # Start positions 0, 1, 2, 3, 4
        if pos + 1 >= len(buffer_bytes):
            continue

        opcode = buffer_bytes[pos]
        modrm = buffer_bytes[pos + 1]

        # Check if it forms a valid 2-byte instruction
        if opcode in MED_OPCODE_SET and is_valid_modrm(modrm):
            # Get junk bytes at the end (based on position)
            junk_after = buffer_bytes[pos + 2 :]

            # Verify junk bytes constraint for 2-byte instructions
            expected_junk_bytes = max(0, 4 - pos)
            if len(junk_after) == expected_junk_bytes:
                return {
                    "type": "2-byte",
                    "name": "Two-byte Med instruction",
                    "instruction": [opcode, modrm],
                    "position": pos,
                    "junk_before": buffer_bytes[:pos],
                    "junk_after": junk_after,
                }

        elif opcode in BIG_OPCODE_SET and is_valid_modrm(modrm):
            # Get junk bytes at the end (based on position)
            junk_after = buffer_bytes[pos + 2 :]

            # Verify junk bytes constraint for 2-byte instructions
            expected_junk_bytes = max(0, 4 - pos)
            if len(junk_after) == expected_junk_bytes:
                return {
                    "type": "2-byte",
                    "name": "Two-byte Big instruction",
                    "instruction": [opcode, modrm],
                    "position": pos,
                    "junk_before": buffer_bytes[:pos],
                    "junk_after": junk_after,
                }

    # 3. Finally check for 1-byte instructions (lowest priority)
    pos = 5  # Only valid position for 1-byte instruction (last byte)
    if pos < len(buffer_bytes):
        byte = buffer_bytes[pos]
        if byte in SINGLE_BYTE_OPCODE_SET:
            return {
                "type": "1-byte",
                "name": "Single-byte big instruction",
                "instruction": [byte],
                "position": pos,
                "junk_before": buffer_bytes[:pos],
                "junk_after": [],  # No junk after 1-byte instruction at the end
            }

    # No valid instruction found
    return {
        "type": None,
        "name": "No match found",
        "instruction": [],
        "position": -1,
        "junk_before": buffer_bytes,
        "junk_after": [],
    }


def filter_match_chains(match_chains: MatchChains) -> list[MatchChains]:
    """
    Filters out match chains that are false positives based on two criteria:
      - The total length of the anti-disassembly routine must be between 12 and 129 bytes.
      - The junk length must be nonzero.
    """
    valid_chains = []
    for chain in ida_helpers.ida_tguidm(match_chains):
        total_length = chain.overall_length()
        junk_length = (
            chain.junk_length
        )  # assumes this property returns the total length of junk instructions
        if junk_length == 0:
            # Likely a false positive since no junk instructions were found.
            continue
        if total_length < 12 or total_length > 129:
            # Stub does not meet size constraints.
            continue
        valid_chains.append(chain)
    return valid_chains


def filter_antidisasm_patterns(
    mem: Memory,
    chains: list[MatchChains],
    start_ea: int,
    min_size: int = 12,
    max_size: int = 129,
) -> list[MatchChains]:
    """
    Filter out false positive anti-disassembly patterns and handle overlaps.
    Integrates with existing big instruction detection code.

    Args:
        chains: List of MatchChain objects
        mem: Memory object containing binary data
        start_ea: Starting effective address
        min_size: Minimum valid size for an anti-disassembly routine (default: 12)
        max_size: Maximum valid size for an anti-disassembly routine (default: 129)

    Returns:
        List of validated MatchChain objects
    """
    logger.info(f"Filtering {len(chains)} potential anti-disassembly patterns...")

    # Stage 1: Basic filtering based on size and junk presence
    logger.info("Stage 1: Basic validation")
    filtered_chains = []

    for chain in ida_helpers.ida_tguidm(chains):

        # Apply basic filters
        length = chain.overall_length()
        if length < min_size or length > max_size:
            logger.debug(
                f"  Rejected: {chain.description} @ 0x{chain.overall_start():X} - length {length} outside valid range {min_size}-{max_size}"
            )
            continue

        if not chain.junk_segments or chain.junk_length == 0:
            logger.debug(
                f"  Rejected: {chain.description} @ 0x{chain.overall_start():X} - no junk instructions"
            )
            continue

        # If big instruction hasn't been detected yet, we'll validate it in Stage 2
        filtered_chains.append(chain)

    logger.info(f"  After basic filtering: {len(filtered_chains)} chains remain")

    # Stage 2: Validate big instructions if not already done
    logger.info("Stage 2: Big instruction validation")
    validated_with_big_instr = []

    for chain in ida_helpers.ida_tguidm(filtered_chains):
        # Check if we already have a big instruction segment
        if any(
            seg.segment_type == SegmentType.BIG_INSTRUCTION for seg in chain.segments
        ):
            validated_with_big_instr.append(chain)
            continue

        # Find the big instruction
        match_start = chain.overall_start()
        chain_end = match_start + max_size

        logger.info(f"Analyzing match: {chain.description} @ 0x{match_start:X}")

        # Determine possible jump targets - using your existing code
        jump_targets = JumpTargetAnalyzer(
            chain.overall_matched_bytes(), match_start, chain_end, start_ea
        ).process(mem=mem, chain=chain)

        big_instr_found = False

        for target in jump_targets:
            # The most_likely_target represents the most likely jump target within the
            # stub—likely the point where execution exits to the unobfuscated code.
            # however, if we do not find a match, then we want to continue searching
            # previous targets and use those in decending order until we find a match
            logger.info(f"most_likely_target: 0x{target:X}, block_end: 0x{chain_end:X}")
            # Check for big instruction in the 6 bytes before target
            # a big instruction (e.g., one with a 32-bit operand, up to 6 bytes)
            # just before the final jump target to confuse disassemblers.
            search_start = target - 6
            if search_start < start_ea:
                continue

            # Extract the 6-byte buffer
            buffer_offset = search_start - start_ea
            target_offset = target - start_ea
            target_offset_forward = target - start_ea + 6
            if buffer_offset < 0 or target_offset > len(mem):
                continue

            if target_offset_forward > len(mem):
                logger.info(
                    f"  Rejected: {chain.description} @ 0x{match_start:X} - target_offset_forward out of bounds: {target_offset_forward}"
                )
                continue
            search_bytes_backwards = mem[buffer_offset:target_offset]
            search_bytes_forwards = mem[target_offset:target_offset_forward]

            for start_offset, search_bytes in [
                (buffer_offset, search_bytes_backwards),
                (target_offset, search_bytes_forwards),
            ]:
                logger.info(f"search_bytes: {search_bytes.hex()}")
                # up to 6 bytes to search for a big instruction.
                if len(search_bytes) != 6:
                    logger.info(
                        f"  Rejected: {chain.description} @ 0x{match_start:X} - search_bytes too long: {len(search_bytes)} bytes"
                    )
                    continue
                result = find_big_instruction(search_bytes, is_x64=IS_X64)

                if not result["type"]:
                    logger.debug("No valid instruction found.")
                    # if we do not find a match, then we want to find the previous targets and use those
                    # in decending order until we find a match
                    continue

                # Found a valid big instruction
                big_instr_found = True

                # check for multiple anti-disassembly bytes after search_start + 6
                # if found, then we want to add them to the new_bytes
                new_len = (
                    len(result["junk_before"])
                    + len(result["instruction"])
                    + len(result["junk_after"])
                )
                new_bytes = (
                    result["junk_before"]
                    + bytes(result["instruction"])
                    + bytes(result["junk_after"])
                )

                # Check for additional anti-disassembly bytes
                for i in itertools.count():
                    extra_offset = start_offset + new_len + i
                    b = mem[extra_offset]
                    if b != ANTI_DISASM_EXTRA_BYTE:
                        if i != 0:
                            logger.debug(
                                f"    Found {i} extra anti-disassembly bytes @ 0x{search_start + 6:X}"
                            )
                        break

                    new_bytes += bytes([b])
                    new_len += 1

                chain.add_segment(
                    MatchSegment(
                        start=start_offset,
                        length=new_len,
                        description=result["name"],
                        matched_bytes=new_bytes,
                        segment_type=SegmentType.BIG_INSTRUCTION,
                    )
                )
                break

            if big_instr_found:
                validated_with_big_instr.append(chain)
                break
            else:
                logger.info(
                    f"  Rejected: {chain.description} @ 0x{chain.overall_start():X} - no valid big instruction found for any jump target"
                )

    logger.info(
        f"  After big instruction validation: {len(validated_with_big_instr)} of {len(chains)} chains remain"
    )

    logger.info("Stage 3: Resolving overlaps")
    # Sort chains by start address
    sorted_chains: list[MatchChains] = sorted(
        validated_with_big_instr, key=lambda c: c.overall_start()
    )
    final_chains: list[MatchChains] = []
    covered_ranges: list[tuple[int, int]] = []

    for chain in ida_helpers.ida_tguidm(sorted_chains):
        chain_start = chain.overall_start()

        # Calculate chain end including the big instruction
        big_instr_segments = [
            seg
            for seg in chain.segments
            if seg.segment_type == SegmentType.BIG_INSTRUCTION
        ]
        if big_instr_segments:
            # Use the end of the big instruction as the chain end
            big_instr = big_instr_segments[-1]
            offset_in_mem = big_instr.start
            chain_end = start_ea + offset_in_mem + big_instr.length
        else:
            # Fallback to overall length if no big instruction (shouldn't happen at this point)
            chain_end = chain_start + chain.overall_length()

        # Check if this chain overlaps with an already accepted chain
        is_covered = False
        for start, end in covered_ranges:
            # Check if this chain starts within a covered range
            if chain_start >= start and chain_start < end:
                logger.info(
                    f"  Rejected overlap: {chain.description} @ 0x{chain_start:X} - starts within existing pattern ({start:X} to {end:X})"
                )
                is_covered = True
                break

        if not is_covered:
            final_chains.append(chain)
            covered_ranges.append((chain_start, chain_end))
            logger.info(
                f"  Accepted: {chain.description} @ 0x{chain_start:X} - valid pattern to 0x{chain_end:X}"
            )

    logger.info(
        f"Filtering complete: {len(final_chains)} of {len(chains)} chains accepted"
    )
    return final_chains


def decompile_function(func_start: int):
    hf = ida_hexrays.hexrays_failure_t()
    ida_hexrays.decompile_func(ida_funcs.get_func(func_start), hf)
    ida_auto.auto_wait()


def get_garbage_blobs(text_seg: ida_segment.segment_t):
    """
    Yields pairs of (garbage_blog_ea, aligned)
    """

    for xref in idautils.XrefsTo(text_seg.start_ea):
        ea = xref.frm
        if idc.get_segm_name(ea) != ".text":
            continue

        if idaapi.print_insn_mnem(ea) == "lea":
            yield xref.to

    if not xref:
        raise StopIteration
    ea = xref.frm
    prev_addr = idc.prev_head(ea)
    next_addr = idc.next_head(ea)

    if idaapi.print_insn_mnem(prev_addr) == "lea":
        gb12 = idc.get_operand_value(prev_addr, 1)
        if gb12 >= ea:
            yield next(idautils.XrefsTo(gb12)).to

    elif idaapi.print_insn_mnem(next_addr) == "lea":
        gb12 = idc.get_operand_value(next_addr, 1)
        if gb12 >= ea:
            yield next(idautils.XrefsTo(gb12)).to
    else:
        raise ValueError("No lea rdi or lea rdx instruction found")


def get_tls_region(text_seg: ida_segment.segment_t):
    blobs = []
    for xref in get_garbage_blobs(text_seg):
        # the garbage blobs have minimum length of 0x1000 to
        # maximum 0x2000 (hardcoded!)
        # so we align the garbage blog ea to the nearest multiple of 0x1000
        # aligned = get_aligned_offset(xref.to)
        blobs.append(xref)
    blobs.sort()
    return blobs


def process(start_ea: int, end_ea: int, patch_manager: PatchManager):
    mem = Memory.from_ida_range(start_ea, end_ea)
    chains: MatchChains = find_stage1(mem, start_ea, end_ea)
    if not chains:
        logger.info("No stage1 matches found!")
        return

    chains: MatchChains = find_junk_instructions_after_stage1(
        mem, chains, start_ea, end_ea
    )
    chain_list: list[MatchChains] = filter_match_chains(chains)
    chain_list: list[MatchChains] = filter_antidisasm_patterns(
        mem, chain_list, start_ea
    )
    logger.info("=== Updated matches ===")
    chain_list.sort()
    for chain in chain_list:
        logger.info(chain)
        patch_manager.add_patch(chain.overall_start(), b"\x90" * chain.overall_length())
    logger.info(
        "Analysis completed. Found {} patch operations.".format(len(patch_manager))
    )
    return patch_manager


def execute_action(
    start_ea: int, end_ea: int, patch_manager: PatchManager, force_analyze=False
):
    """
    Main entry point for script.

    Args:
        patch: Whether to apply patches immediately
        using_combined_approach: Whether to use the combined stage1/deflow approach
    """
    logger.info(f"Starting search from: 0x{start_ea:X} to 0x{end_ea:X}")
    process(start_ea, end_ea, patch_manager)
    logger.info("Search completed.")
    patch_manager.apply_all()
    if force_analyze:
        logger.info("Force analyzing...")
        ForceAnalyzeActionHandler.reanalyze_function(start_ea, end_ea)
        logger.info("Force analysis completed.")


ACTION_NAME = "mutilz:remove_anti_disassembly"


@dataclasses.dataclass
class RemoveAntiDisassemblyActionHandler(ida_helpers.BaseActionHandler):
    """Remove Anti Disassembly"""

    action_name: str = ACTION_NAME
    action_label: str = "Remove Anti Disassembly"
    icon: int = 19

    def get_selected_addresses(self):
        is_selected, start_ea, end_ea = idaapi.read_range_selection(
            idaapi.get_current_viewer()
        )
        if is_selected and start_ea != idaapi.BADADDR and end_ea != idaapi.BADADDR:
            # reset ea to start_ea since we selected a range specifically to the
            # start and end of the range
            return start_ea, end_ea

        print("No range selected!")
        if not start_ea:
            start_ea = idaapi.get_screen_ea()
            print(
                f"Cannot determine start address, using current address: 0x{start_ea:X}"
            )
        end_ea = ida_kernwin.ask_addr(start_ea, "Enter end address for selection:")
        if end_ea is None:
            print("Selection canceled. Returning start address.")
            return start_ea, None
        if end_ea <= start_ea:
            print("Error: End address must be greater than start address.")
            return start_ea, None
        return start_ea, end_ea

    @staticmethod
    def settings() -> mutilz.settings.ActionSettings:
        mutilz.settings.reload()
        return mutilz.settings.get_action_config(ACTION_NAME)

    @staticmethod
    def patch_manager(dry_run: bool = False) -> PatchManager:
        settings = RemoveAntiDisassemblyActionHandler.settings()
        patch_mode_name = settings.get("patch_mode", "put")
        patch_mode = PatchManager.Mode._member_map_.get(
            patch_mode_name.upper(), PatchManager.Mode.PUT
        )
        return PatchManager(patch_mode=patch_mode, dry_run=dry_run)

    def activate(self, ctx):
        ea = idaapi.get_screen_ea()
        settings = self.settings()
        load_text_section = settings.getboolean("load_text_section", False)
        force_analyze = settings.getboolean("force_analyze", False)
        clear_output = settings.getboolean("clear_output", False)
        log_level = settings.get_log_level()
        configure_logging(log=logger, level=log_level)

        dry_run = settings.getboolean("dry_run", True)
        patch_manager = self.patch_manager(dry_run=dry_run)

        func = ida_funcs.get_func(ea)
        if func:
            start_ea = func.start_ea
            end_ea = func.end_ea
        elif load_text_section:
            text_seg = ida_segment.get_segm_by_name(".text")
            _, start_ea = get_tls_region(text_seg)
            end_ea = text_seg.end_ea
        else:
            start_ea, end_ea = self.get_selected_addresses()
        try:
            if clear_output:
                clear_output()
            execute_action(start_ea, end_ea, patch_manager, force_analyze=force_analyze)
        finally:
            idc.jumpto(start_ea)

    def update(self, ctx):
        match ctx.widget_type:
            case idaapi.BWN_DISASM:
                return idaapi.AST_ENABLE_FOR_WIDGET
            case _:
                return idaapi.AST_DISABLE_FOR_WIDGET


class RemoveAntiDisassemblyAction(
    actions.action_t, metaclass=ida_helpers.HookedActionMeta
):
    uihook_class = functools.partial(
        ida_helpers.PopUpHook,
        RemoveAntiDisassemblyActionHandler,
        ida_helpers.is_disassembly_widget,
    )


# retrieve the action
def get_action() -> actions.action_t:
    return RemoveAntiDisassemblyAction()
