#!/usr/bin/env python3
"""
Build a self-contained metadata module (plugins/d810/tests/unit/z3_rule_metadata.py)
from

  • a tab-delimited <name>\t<rule> list
  • the existing test_z3_simplifications.py source, so we can
    inherit its  KNOWN_INCORRECT_RULES  comments automatically.
"""
from __future__ import annotations

import argparse
import csv
import re
import textwrap
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class RuleInfo:
    name: str
    expr: str
    known_incorrect: bool = False
    comment: str | None = None


# ──────────────────────────────────────────────────────────────────────────
def _parse_known_incorrect(test_file: Path) -> dict[str, str | None]:
    """Return {rule_expr: comment_text|None} from the test source."""
    in_dict, last_comment, mapping = False, "", {}

    for line in test_file.read_text().splitlines():
        if line.strip().startswith("KNOWN_INCORRECT_RULES"):
            in_dict = True
            continue
        if not in_dict:
            continue
        if line.strip().startswith("}"):
            break  # end of the dict literal
        if line.lstrip().startswith("#"):
            # remember the explanatory comment that precedes the next entry
            last_comment = line.split("#", 1)[1].strip()
            continue
        m = re.search(r'"([^"]+)"', line)
        if m:
            rule = m.group(1)
            mapping[rule] = last_comment or None
            last_comment = ""

    return mapping


# ──────────────────────────────────────────────────────────────────────────
def main(tsv: Path, test_src: Path, out: Path) -> None:
    known_map = _parse_known_incorrect(test_src)

    # build the master list of RuleInfo objects
    rules: list[RuleInfo] = []
    with tsv.open(newline="") as fh:
        reader = csv.reader(fh, delimiter="\t")
        for row in reader:
            if len(row) < 2:
                continue
            name, expr = row[0].strip(), row[1].strip()
            rules.append(
                RuleInfo(
                    name=name,
                    expr=expr,
                    known_incorrect=expr in known_map,
                    comment=known_map.get(expr),
                )
            )

    # render the metadata module
    entries = ",\n".join(
        "    RuleInfo("
        f"name={r.name!r}, expr={r.expr!r}, "
        f"known_incorrect={r.known_incorrect}, comment={r.comment!r})"
        for r in rules
    )

    module_text = textwrap.dedent(
        f"""
\"\"\"Autogenerated by build_z3_rule_metadata.py - DO NOT EDIT BY HAND\"\"\"

from dataclasses import dataclass

@dataclass(frozen=True, slots=True)
class RuleInfo:
    name: str
    expr: str
    known_incorrect: bool = False
    comment: str | None = None


RULES: list[RuleInfo] = [
{entries}
]

# convenient helpers
RULE_BY_EXPR = {{r.expr: r for r in RULES}}
KNOWN_INCORRECT_RULES = {{r.expr for r in RULES if r.known_incorrect}}
"""
    )

    out.write_text(module_text.strip() + "\n")
    print(f"Wrote metadata for {len(rules)} rules → {out}")


if __name__ == "__main__":
    here = Path(__file__).resolve()
    default_test = (
        here.parent.parent / "plugins/d810/tests/unit/test_z3_simplifications.py"
    )
    default_out = here.parent.parent / "plugins/d810/tests/unit/z3_rule_metadata.py"

    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=Path, help="tab-separated rule list")
    ap.add_argument("--test-src", type=Path, default=default_test)
    ap.add_argument("--out", type=Path, default=default_out)
    main(**vars(ap.parse_args()))
